name: "Say Hello From Thiti"
description: "A demo composite action that prints a hello message"
runs:
  using: "composite"
  steps:
    - name: Say Hello
      shell: bash
      run: echo "👋 Hello from thiti!"
