name: DEV CI

on:
  push:
    branches: [dev]

jobs:
  dev-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run hello.py
        run: python hello.py
        continue-on-error: true # Allow failure:true

      - uses: ./.github/actions/say-from-thiti

      # On Success of the previous step
      - name: on success
        if: success() # Only run if the previous step succeeded
        run: |
          echo "It works!"

      - name: Simulate DEV deploy
        run: echo "Simulating deployment to DEV environment"

  alpine-job:
    uses: ./.github/jobs/say-alpine.yml
